#!/usr/bin/env python
# -*- coding: UTF-8 -*-

#######################################
#                                     #
#     Doxing Framework install        #
#                                     #
#######################################

# noinspection PyUnresolvedReferences
import os, time, subprocess
from sys import stdout
from libs.modules import DetectPyVersion
# noinspection PyUnresolvedReferences
from libs.colors import *
# noinspection PyUnresolvedReferences
from libs.view import *

if os.name == "nt":
    os.system("cls")
elif os.name == "posix":
    os.system("clear")
else:
    pass

DetectPyVersion()


print Yellow +"               ______  "+ Green +" _______  __   __  ___   __    _  _______                    "+ Red +"               ____             "
print Yellow +"              |      | "+ Green +"|       ||  |_|  ||___| |  |  | ||       |                   "+ Red +"        _,-ddd888888bbb-._      "
print Yellow +"              |  _    |"+ Green +"|   _   ||       | ___  |   |_| ||    ___|                   "+ Red +"      d88888888888888888888b    "
print Yellow +"              | | |   |"+ Green +"|  | |  ||       ||   | |       ||   | __                    "+ Red +"    d888888888888888888888888b  "
print Yellow +"              | |_|   |"+ Green +"|  |_|  | |     | |   | |  _    ||   ||  |                   "+ Red +"   6888888888888888888888888889 "
print Yellow +"              |       |"+ Green +"|       ||   _   ||   | | | |   ||   |_| |                   "+ Red +"   68888b8##8q8888888p8##8d88889"
print Yellow +"              |______| "+ Green +"|_______||__| |__||___| |_|  |__||_______|                   "+ Red +"   `d8887     p88888q     4888b'"
print Yellow +"   _______ "+ Green +" ______    _______ "+ Yellow +" __   __ "+ Green +" _______  _     _  _______  ______    ___   _   "+ Red +" `d8887    p88888q    4888b' "
print Yellow +"  |       |"+ Green +"|    _ |  |   _   |"+ Yellow +"|  |_|  |"+ Green +"|       || | _ | ||       ||    _ |  |   | | |  "+ Red +"   `d887   p88888q   488b'   "
print Yellow +"  |    ___|"+ Green +"|   | ||  |  |_|  |"+ Yellow +"|       |"+ Green +"|    ___|| || || ||   _   ||   | ||  |   |_| |  "+ Red +"      `d88888888888888d'     "
print Yellow +"  |   |___ "+ Green +"|   |_||_ |       |"+ Yellow +"|       |"+ Green +"|   |___ |       ||  | |  ||   |_||_ |      _|  "+ Red +"         `d88888888b'        "
print Yellow +"  |    ___|"+ Green +"|    __  ||       |"+ Yellow +"|       |"+ Green +"|    ___||       ||  |_|  ||    __  ||     |_   "+ Red +"           `d8888b'          "
print Yellow +"  |   |    "+ Green +"|   |  | ||   _   |"+ Yellow +"| ||_|| |"+ Green +"|   |___ |   _   ||       ||   |  | ||    _  |  "+ Red +"             `bd'            "
print Yellow +"  |___|    "+ Green +"|___|  |_||__| |__|"+ Yellow +"|_|   |_|"+ Green +"|_______||__| |__||_______||___|  |_||___| |_|  "+ Red +"                             "

if os.name == "posix":
    print Cyan + '\n                     ╔════════════════════════════════╗'
    print Green + '                              INSTALLING TOOL          '
    print Cyan + '                     ╚════════════════════════════════╝'
    print White
else:
    print Cyan + '\n                                                     '
    print Green + '                      INSTALLING TOOL                  '
    print Cyan + '                                                       '
    print White


def Command_exe(msg, cmd):
    i = "\033[1mSTATUS" + White + "::[Processing]"
    stdout.write(" " + msg + " %s" % i)
    stdout.flush()
    os.system(cmd)
    j = "[\033[1m" + Green + "OK" + White + "]"
    stdout.write("\r " + msg + " STATUS::%s" % j)

if os.name == "nt":
    print " [" + Red + "-" + White + "] ERROR::" + Blue + " DoxingFramework " + Blue + " only can be installed in " + Red + "Linux" + White + "."
    exit(1)


if os.getuid() != 0:
    print " [" + Red + "-" + White + "] ERROR::" + Blue + " DoxingFramework Install" + Blue + " must be run as " + Red + "root" + White + "."
    print " [" + Red + "-" + White + "] login as root (" + Red + "sudo" + White + ") or try " + White + "sudo python install" + White + "\n"
    exit(1)

time.sleep(1)


print Yellow + "   INSTALLING THE FRAMEWORK....\n"
print Command_exe("[" +time.strftime('%H:%M:%S')+"] Creating Folder.                 ",'mkdir /usr/share/DoxingFramework')
time.sleep(2)
print Command_exe("[" +time.strftime('%H:%M:%S')+"] Copying files.                   ",'cp DoxingFramework /usr/local/bin && cp -r libs /usr/share/DoxingFramework')
time.sleep(2)
print Command_exe("[" +time.strftime('%H:%M:%S')+"] Giving privileges.               ",'chmod +x /usr/local/bin/DoxingFramework')
time.sleep(3)

print Green + "\n[OK]" + White + " DoxingFramework was installed, use DoxingFramework to start the tool"
print Green + "\n[OK]" + White + " Go to " + Blue + "https://github.com/Sempatte/DoxingFramework for more info\n"

