#!/usr/bin/env python
# -*- coding: UTF-8 -*-

#######################################
#                                     #
#     Doxing Framework uninstall       #
#                                     #
#######################################

# noinspection PyUnresolvedReferences
import os, time, subprocess
from sys import stdout
# noinspection PyUnresolvedReferences
from libs import colors
# noinspection PyUnresolvedReferences
from libs.view import *

if os.name == "nt":
    os.system("cls")
elif os.name == "posix":
    os.system("clear")
else:
    pass

from libs.modules import DetectPyVersion
DetectPyVersion()

print colors.Yellow +"               ______  "+ colors.Green +" _______  __   __  ___   __    _  _______                    "+ colors.Red +"               ____             "
print colors.Yellow +"              |      | "+ colors.Green +"|       ||  |_|  ||___| |  |  | ||       |                   "+ colors.Red +"        _,-ddd888888bbb-._      "
print colors.Yellow +"              |  _    |"+ colors.Green +"|   _   ||       | ___  |   |_| ||    ___|                   "+ colors.Red +"      d88888888888888888888b    "
print colors.Yellow +"              | | |   |"+ colors.Green +"|  | |  ||       ||   | |       ||   | __                    "+ colors.Red +"    d888888888888888888888888b  "
print colors.Yellow +"              | |_|   |"+ colors.Green +"|  |_|  | |     | |   | |  _    ||   ||  |                   "+ colors.Red +"   6888888888888888888888888889 "
print colors.Yellow +"              |       |"+ colors.Green +"|       ||   _   ||   | | | |   ||   |_| |                   "+ colors.Red +"   68888b8##8q8888888p8##8d88889"
print colors.Yellow +"              |______| "+ colors.Green +"|_______||__| |__||___| |_|  |__||_______|                   "+ colors.Red +"   `d8887     p88888q     4888b'"
print colors.Yellow +"   _______ "+ colors.Green +" ______    _______ "+ colors.Yellow +" __   __ "+ colors.Green +" _______  _     _  _______  ______    ___   _   "+ colors.Red +" `d8887    p88888q    4888b' "
print colors.Yellow +"  |       |"+ colors.Green +"|    _ |  |   _   |"+ colors.Yellow +"|  |_|  |"+ colors.Green +"|       || | _ | ||       ||    _ |  |   | | |  "+ colors.Red +"   `d887   p88888q   488b'   "
print colors.Yellow +"  |    ___|"+ colors.Green +"|   | ||  |  |_|  |"+ colors.Yellow +"|       |"+ colors.Green +"|    ___|| || || ||   _   ||   | ||  |   |_| |  "+ colors.Red +"      `d88888888888888d'     "
print colors.Yellow +"  |   |___ "+ colors.Green +"|   |_||_ |       |"+ colors.Yellow +"|       |"+ colors.Green +"|   |___ |       ||  | |  ||   |_||_ |      _|  "+ colors.Red +"         `d88888888b'        "
print colors.Yellow +"  |    ___|"+ colors.Green +"|    __  ||       |"+ colors.Yellow +"|       |"+ colors.Green +"|    ___||       ||  |_|  ||    __  ||     |_   "+ colors.Red +"           `d8888b'          "
print colors.Yellow +"  |   |    "+ colors.Green +"|   |  | ||   _   |"+ colors.Yellow +"| ||_|| |"+ colors.Green +"|   |___ |   _   ||       ||   |  | ||    _  |  "+ colors.Red +"             `bd'            "
print colors.Yellow +"  |___|    "+ colors.Green +"|___|  |_||__| |__|"+ colors.Yellow +"|_|   |_|"+ colors.Green +"|_______||__| |__||_______||___|  |_||___| |_|  "+ colors.Red +"                             "
if os.name == "posix":
    print colors.Cyan + '\n                              ╔════════════════════════════════╗'
    print colors.Green + '                                    UNINSTALLING TOOL           '
    print colors.Cyan + '                              ╚════════════════════════════════╝'
    print colors.White
else:
    print colors.Cyan + '\n                                                              '
    print colors.Green + '                           UNINSTALLING TOOL                    '
    print colors.Cyan + '                                                                '
    print colors.White


def Command_exe(msg, cmd):
    i = "\033[1mSTATUS" + colors.White + "::[Processing]"
    stdout.write(" " + msg + " %s" % i)
    stdout.flush()
    os.system(cmd)
    j = "[\033[1m" + colors.Green + "OK" + colors.White + "]"
    stdout.write("\r " + msg + " STATUS::%s" % j)


if os.name == "nt":
    print " [" + colors.Red + "-" + colors.White + "] ERROR:" + colors.Blue + " DoxingFramework" + colors.Blue + " only can be install in " + colors.Red + "Linux" + colors.White + "."
    exit(1)

if os.getuid() != 0:
    print " [" + colors.Red + "-" + colors.White + "] ERROR:" + colors.Blue + " DoxingFramework Install" + colors.Blue + " must be run as " + colors.Red + "root" + colors.White + "."
    print " [" + colors.Red + "-" + colors.White + "] login as root (" + colors.Red + "sudo" + colors.White + ") or try " + colors.White + "sudo python uninstall" + colors.White + "\n"
    exit(1)

time.sleep(1)


print colors.Yellow + "   UNINSTALLING THE FRAMEWORK...\n"
print Command_exe("[" +time.strftime('%H:%M:%S')+"] Deleting Folders.                 ",'rm -r /usr/share/DoxingFramework')
time.sleep(2)
print Command_exe("[" +time.strftime('%H:%M:%S')+"] Deleting Files.                   ",'rm -f /usr/local/bin/DoxingFramework')
time.sleep(3)


print colors.Green + "\n[OK]" + colors.White + " DoxingFramework was uninstalled" + colors.Yellow + ' ,thanks for use' + colors.Green + ' |DoxingFramework|\n' + colors.White